version: '3.8'

services:
  app-one:
    build:
      context: .
      dockerfile: apps/app-one/Dockerfile
    ports:
      - "8081:80"
    restart: always

  app-two:
    build:
      context: .
      dockerfile: apps/app-two/Dockerfile
    ports:
      - "8082:80"
    restart: always
